Document: libgea
Title: Debian libgea Manual
Author: <insert document author here>
Abstract: This manual describes what libgea is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libgea/libgea.sgml.gz

Format: postscript
Files: /usr/share/doc/libgea/libgea.ps.gz

Format: text
Files: /usr/share/doc/libgea/libgea.text.gz

Format: HTML
Index: /usr/share/doc/libgea/html/index.html
Files: /usr/share/doc/libgea/html/*.html

  
